spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://my-host.com:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: true

logging:
  level:
    com.example: debug